### ISSUE TITLE
Reorganize repos

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/ckan#32]
**Is your feature request related to a problem? Please describe.**
- The main repository is a forked repo of ckan, but our work doesn't match the use case of a fork in my opinion (contribution to the main repo or building a new product from an existing codebase).
Working with a forked repository will make it harder to upgrade with new CKAN releases.
- The cioos ckan code is scattered accross several repositories: the main and submodules (some of them are third party repos, some of them are cioos). The current practice is to create a forked repository when an existing plugin needs to be customized. This practice creates too many repositories for just a few changes and complexify the project with no benefit in my opinion.

**Describe the solution you'd like**
Here is what the target could look like:
https://docs.google.com/presentation/d/1O9zf2TToXOPenB9OSGV-R72IgFusoGOoLwouei6PwWE/edit?usp=sharing

- Only one repository for CIOOS CKAN common code (one plugin).
- One repository per RA for RA spécific code (one plugin per RA to alter theme style or else)
- A docker image based the ckan official codebase
- A docker image based on the CIOOS CKAN code and overriding the previously mentioned image
- A docker image per RA based on CKAN RA specific code and overriding the previously mentioned image

**Comment by fostermh** [comment]
Thanks for this. I like the diagram.

just a quick note that we could and likely should generate the 'CIOOS CKAN base image' right now with our existing codebase. combining the 3 cioos plugins is doable with minimal effort. I had initially thought that the separate repos would evolve into contributions back to the public repos of scheming, spatial, fluent, etc and we would be left with just the theme repo. Not unexpectedly there has been little time for that.

I am a little concerned with the mention of 'RA specific code' I agree that each RA will have their own configuration settings, css, images, and WordPress content but I would like to see any ckan 'code' shared between all the RA's. Perhaps I am just not able to visualize a situation where separate code per RA would be needed.

Overall I think this is a great start and I look forward to more discussion on this topic.

**Comment by ogsletcax** [comment]
About the 'CIOOS CKAN base image' here is the pipeline i use on gitlab to generate this.
Maybe we could work on moving it to github, circle-ci or else and use the cioos docker repository mentioned in https://github.com/cioos-siooc/ckan/issues/28 ? 

```yaml
run-build-base:
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:dind
    stage: build_base
    script:
      - apk add git
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      # Initialisation du projet
      - git clone -b cioos https://github.com/cioos-siooc/ckan.git
      - cd ./ckan
      - git checkout cioos
      - git submodule init
      - git submodule update 
      - cd ./contrib/docker/
      - cp .env.template .env
      - cp production_root_url.ini production.ini
      - cp who_root_url.ini who.ini
      - cp ./pycsw/pycsw.cfg.template ./pycsw/pycsw.cfg
      - cd ../../
      - TAG=$(date +%F)
      # Build and push solr image
      - docker build -t ogsletcax/cioos-ckan-solr:$TAG --file ./contrib/docker/solr/Dockerfile .
      - docker push ogsletcax/cioos-ckan-solr:$TAG
      # Build and push postgres image
      - docker build -t ogsletcax/cioos-ckan-postgresql:$TAG --file ./contrib/docker/postgresql/Dockerfile .
      - docker push ogsletcax/cioos-ckan-postgresql:$TAG
      # Build and push ckan image
      - docker build -t ogsletcax/cioos-ckan:$TAG .
      - docker push ogsletcax/cioos-ckan:$TAG
      # Nettoyage pour liberer de la place
      - docker rmi ogsletcax/cioos-ckan-solr:$TAG
      - docker rmi ogsletcax/cioos-ckan-postgresql:$TAG
      - docker rmi ogsletcax/cioos-ckan:$TAG
    tags:
      - dind
    when: manual
```
